import Database from 'better-sqlite3';
import { strFromU8, unzipSync } from 'fflate';
import { describe, expect, it } from 'vitest';
import { AppError } from '../api/errors.js';
import {
  assertExportReady,
  createApplication,
  resolveConfirmations,
  setFactConfirmations,
  updateApplication,
} from '../db/repositories/applications.js';
import { extractFactAssertions } from '../prose/facts.js';
import { CHECKLIST_SCOPE_NOTE, draftToMarkdown, markdownToDraft } from './draft.js';
import { draftToDocx } from './docx.js';

const MD = [
  '# Need statement',
  '',
  'The W8UM club station has run on a 1998 transceiver since 2019.',
  '',
  '- Replace the transceiver',
  '- Train 12 new operators',
  '',
  '[TODO: how many members hold a General class licence?]',
  '',
  '# Budget',
  '',
  'One IC-7610 at $2,899.',
].join('\n');

const META = {
  title: 'ARDC Grants Program — draft',
  subtitle: 'University of Michigan Amateur Radio Club (W8UM)',
  factChecklist: ['$2,899 unit price', '12 new operators', '1998 transceiver'],
  disclosure:
    'Portions of this application were drafted with the assistance of a large language model; all facts were verified by the applicant.',
  provenanceNote:
    'Generated by GrantSpotter on 2026-08-02. Every figure above is the applicant’s responsibility.',
};

// ---------------------------------------------------------------------------
// Readers that open the archive and read the parts, never the byte length.
// ---------------------------------------------------------------------------

function parts(buf: Buffer | Uint8Array): Record<string, Uint8Array> {
  return unzipSync(new Uint8Array(buf));
}

function documentXml(buf: Buffer | Uint8Array): string {
  const part = parts(buf)['word/document.xml'];
  expect(part, 'word/document.xml must exist in the archive').toBeDefined();
  return strFromU8(part as Uint8Array);
}

function decodeXml(value: string): string {
  return value
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, '&');
}

/** Every `<w:t>` run in document order — what a reader of the Word file actually sees. */
function runs(xml: string): string[] {
  return [...xml.matchAll(/<w:t(?: [^>]*)?>([\s\S]*?)<\/w:t>/g)].map((m) => decodeXml(m[1] as string));
}

/** The visible text, one entry per `<w:p>`, runs concatenated. This is the readable document. */
function paragraphs(xml: string): string[] {
  return [...xml.matchAll(/<w:p(?: [^>]*)?>([\s\S]*?)<\/w:p>/g)].map((m) => runs(m[1] as string).join(''));
}

/** The `<w:r>` elements of one paragraph, so a test can ask how a single run is styled. */
function runElements(xml: string, paragraphIndex: number): string[] {
  const paragraph = [...xml.matchAll(/<w:p(?: [^>]*)?>([\s\S]*?)<\/w:p>/g)][paragraphIndex]?.[1] ?? '';
  return [...paragraph.matchAll(/<w:r>[\s\S]*?<\/w:r>/g)].map((m) => m[0]);
}

// ---------------------------------------------------------------------------
// markdownToDraft
// ---------------------------------------------------------------------------

describe('markdownToDraft', () => {
  it('splits on the shallowest heading level and keeps paragraph order', () => {
    const draft = markdownToDraft(MD, META);
    expect(draft.sections.map((s) => s.heading)).toEqual(['Need statement', 'Budget']);
    expect(draft.sections[0]?.blocks[0]).toEqual({
      kind: 'p',
      text: 'The W8UM club station has run on a 1998 transceiver since 2019.',
    });
  });

  it('groups consecutive dash bullets into one bullet block', () => {
    const draft = markdownToDraft(MD, META);
    expect(draft.sections[0]?.blocks[1]).toEqual({
      kind: 'bullet',
      items: ['Replace the transceiver', 'Train 12 new operators'],
    });
  });

  it('classifies a [TODO: ...] line as a todo block, not a paragraph', () => {
    const draft = markdownToDraft(MD, META);
    expect(draft.sections[0]?.blocks[2]).toEqual({
      kind: 'todo',
      text: '[TODO: how many members hold a General class licence?]',
    });
  });

  it('puts content before the first heading into an untitled leading section', () => {
    const draft = markdownToDraft('Intro line.\n\n# Body\n\ntext', META);
    expect(draft.sections[0]?.heading).toBe('');
    expect(draft.sections[0]?.blocks[0]).toEqual({ kind: 'p', text: 'Intro line.' });
  });

  /**
   * EVERY TEMPLATE THIS PRODUCT SHIPS USES `##` FOR ITS HEADINGS — 120 of them under `content/`,
   * and not one `#`. A splitter that only knows `#` flattens a filled template into ONE untitled
   * section whose section titles have become body paragraphs, which is the whole document.
   */
  it('splits a level-2 document into sections too, because the shipped templates are all level 2', () => {
    const draft = markdownToDraft('## What this section has to do\n\nShow the work.\n\n## Skeleton\n\nRows.', META);
    expect(draft.sections.map((s) => s.heading)).toEqual(['What this section has to do', 'Skeleton']);
  });

  it('keeps a deeper heading as a heading block rather than dissolving it into prose', () => {
    const draft = markdownToDraft('# Top\n\n## Inner\n\nbody', META);
    expect(draft.sections.map((s) => s.heading)).toEqual(['Top']);
    expect(draft.sections[0]?.blocks[0]).toEqual({ kind: 'heading', level: 2, text: 'Inner' });
  });

  it('keeps an ordered list as an ordered list instead of one run-on paragraph', () => {
    const draft = markdownToDraft('# S\n\n1. Order the radio\n2. Install the feedline', META);
    expect(draft.sections[0]?.blocks[0]).toEqual({
      kind: 'ordered',
      items: ['Order the radio', 'Install the feedline'],
    });
  });

  it('keeps a blockquote separate, because template guidance is not the applicant’s own prose', () => {
    const draft = markdownToDraft('# S\n\n> Do not write: "materials will be procured".', META);
    expect(draft.sections[0]?.blocks[0]).toEqual({
      kind: 'quote',
      lines: ['Do not write: "materials will be procured".'],
    });
  });

  it('parses a pipe table into rows and drops the alignment rule', () => {
    const draft = markdownToDraft('# S\n\n| Phase | Who |\n|---|---|\n| 1 | Dana |', META);
    expect(draft.sections[0]?.blocks[0]).toEqual({
      kind: 'table',
      rows: [
        ['Phase', 'Who'],
        ['1', 'Dana'],
      ],
    });
  });

  /**
   * SPEC §10.1. `fillTemplate` substitutes a slot IN PLACE, so the overwhelmingly common gap is
   * mid-sentence, not on a line of its own. The line-only classifier the brief specified read an
   * inline gap as ordinary prose, and ordinary prose is rendered as ordinary prose — a sentence
   * that asserts nothing while looking complete.
   */
  it('leaves an inline gap inside its sentence, byte for byte', () => {
    const draft = markdownToDraft(
      '# S\n\nThe station operates from [TODO: club.venue — where the station lives] on campus.',
      META,
    );
    expect(draft.sections[0]?.blocks[0]).toEqual({
      kind: 'p',
      text: 'The station operates from [TODO: club.venue — where the station lives] on campus.',
    });
  });

  /**
   * `farweb.org` is the Foundation for Amateur Radio's hijacked domain, now redirecting to a
   * gambling site while ARRL and QCWA pages still send applicants there. `redactBlockedLinks` is
   * the product's existing answer and this is its second call site.
   */
  it('withholds a blocklisted address instead of carrying it into the document', () => {
    const draft = markdownToDraft('# S\n\nApply at https://www.farweb.org/scholarships before May.', META);
    const text = (draft.sections[0]?.blocks[0] as { text: string }).text;
    expect(text).not.toMatch(/farweb/i);
    expect(text).toContain('link withheld');
    expect(text).toContain('before May');
  });
});

// ---------------------------------------------------------------------------
// draftToMarkdown
// ---------------------------------------------------------------------------

describe('draftToMarkdown', () => {
  it('round-trips headings, bullets and todos', () => {
    const md = draftToMarkdown(markdownToDraft(MD, META));
    expect(md).toContain('# Need statement');
    expect(md).toContain('- Train 12 new operators');
    expect(md).toContain('[TODO: how many members hold a General class licence?]');
    expect(md).toContain('## Fact checklist');
    expect(md).toContain('$2,899 unit price');
  });

  it('re-emits ordered lists, quotes and tables rather than flattening them', () => {
    const source = '# S\n\n1. First\n\n> Guidance line.\n\n| A | B |\n|---|---|\n| 1 | 2 |';
    const md = draftToMarkdown(markdownToDraft(source, META));
    expect(md).toContain('1. First');
    expect(md).toContain('> Guidance line.');
    expect(md).toContain('| A | B |');
    expect(md).toContain('| 1 | 2 |');
  });

  it('says in writing that the checklist cannot list a claim made only in words', () => {
    const md = draftToMarkdown(markdownToDraft(MD, META));
    expect(md).toContain(CHECKLIST_SCOPE_NOTE);
    for (const word of ['superlative', 'universal', 'causal', 'faculty advisor']) {
      expect(CHECKLIST_SCOPE_NOTE.toLowerCase()).toContain(word);
    }
  });
});

// ---------------------------------------------------------------------------
// draftToDocx
// ---------------------------------------------------------------------------

describe('draftToDocx', () => {
  it('produces a ZIP container holding word/document.xml', async () => {
    const buf = await draftToDocx(markdownToDraft(MD, META));
    expect(buf.subarray(0, 2).toString('latin1')).toBe('PK');
    expect(Object.keys(parts(buf))).toContain('word/document.xml');
  });

  it('is still a readable OPC package after the timestamps are normalised', async () => {
    const buf = await draftToDocx(markdownToDraft(MD, META), { generatedAtISO: '2026-08-02T12:00:00.000Z' });
    const entries = parts(buf);
    for (const required of ['[Content_Types].xml', '_rels/.rels', 'word/document.xml', 'word/styles.xml']) {
      expect(Object.keys(entries)).toContain(required);
    }
    expect(strFromU8(entries['[Content_Types].xml'] as Uint8Array)).toContain(
      'wordprocessingml.document.main+xml',
    );
    expect(strFromU8(entries['docProps/core.xml'] as Uint8Array)).toContain('2026-08-02T12:00:00.000Z');
  });

  it('carries the title, headings, bullet text, TODO marker, fact checklist and disclosure', async () => {
    const xml = documentXml(await draftToDocx(markdownToDraft(MD, META)));
    expect(xml).toContain('ARDC Grants Program');
    expect(xml).toContain('Need statement');
    expect(xml).toContain('Train 12 new operators');
    expect(xml).toContain('how many members hold a General class licence');
    expect(xml).toContain('Fact checklist');
    expect(xml).toContain('large language model');
    expect(xml).toContain('Generated by GrantSpotter on 2026-08-02');
  });

  it('renders TODO text with a highlight so it cannot be shipped unnoticed', async () => {
    const xml = documentXml(await draftToDocx(markdownToDraft(MD, META)));
    expect(xml).toMatch(/<w:highlight w:val="yellow"\/>/);
  });

  /**
   * THE GAP HAS TO SURVIVE INTO WORD AND STILL LOOK LIKE A GAP. `stripTodoMarkers` exists and is
   * an ANALYSIS helper; an applicant-facing renderer that used it would delete the brackets and
   * leave the hint text — `the club's callsign, e.g. W8UM` — sitting in a sentence as though the
   * applicant had written it.
   */
  it('keeps the whole marker, brackets and example included, in the extracted document text', async () => {
    const marker = "[TODO: club.callsign — the club's callsign, e.g. W8UM]";
    const xml = documentXml(await draftToDocx(markdownToDraft(`# S\n\n${marker}`, META)));
    expect(paragraphs(xml)).toContain(marker);
    expect(runs(xml)).toContain(marker);
  });

  it('gives an inline gap its own loud run without disturbing the sentence around it', async () => {
    const sentence = 'The station operates from [TODO: club.venue — where the station lives] on campus.';
    const xml = documentXml(await draftToDocx(markdownToDraft(`# S\n\n${sentence}`, META)));
    const index = paragraphs(xml).indexOf(sentence);
    expect(index, 'the sentence must survive intact').toBeGreaterThan(-1);
    const [before, gap, after] = runElements(xml, index);
    expect(before).toContain('The station operates from ');
    expect(before).not.toContain('<w:highlight');
    expect(gap).toContain('[TODO: club.venue — where the station lives]');
    expect(gap).toContain('<w:highlight w:val="yellow"/>');
    expect(gap).toContain('<w:b/>');
    expect(gap).toContain('<w:color w:val="B00020"/>');
    expect(after).toContain(' on campus.');
    expect(after).not.toContain('<w:highlight');
  });

  it('makes a gap inside a bullet just as loud as one in a paragraph', async () => {
    const xml = documentXml(
      await draftToDocx(markdownToDraft('# S\n\n- Train [TODO: project.traineeCount — how many] operators', META)),
    );
    const index = paragraphs(xml).indexOf('Train [TODO: project.traineeCount — how many] operators');
    expect(index).toBeGreaterThan(-1);
    expect(runElements(xml, index).some((r) => r.includes('<w:highlight w:val="yellow"/>'))).toBe(true);
  });

  it('prints the checklist scope note, so the packet never implies everything was verified', async () => {
    const xml = documentXml(await draftToDocx(markdownToDraft(MD, META)));
    expect(paragraphs(xml).join('\n')).toContain(CHECKLIST_SCOPE_NOTE);
  });

  it('renders a table as a Word table rather than a wall of pipe characters', async () => {
    const xml = documentXml(
      await draftToDocx(markdownToDraft('# S\n\n| Phase | Who |\n|---|---|\n| 1 | Dana |', META)),
    );
    expect(xml).toContain('<w:tbl>');
    expect(runs(xml)).toEqual(expect.arrayContaining(['Phase', 'Who', '1', 'Dana']));
    expect(runs(xml).join('')).not.toContain('|---|');
  });

  it('is byte-identical across two runs when the generation instant is stated', async () => {
    const draft = markdownToDraft(MD, META);
    const opts = { generatedAtISO: '2026-08-02T12:00:00.000Z' };
    const a = await draftToDocx(draft, opts);
    const b = await draftToDocx(draft, opts);
    expect(a.equals(b)).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// The same document, written on a machine that is not this one
// ---------------------------------------------------------------------------

/**
 * THE TEST ABOVE PROVED THE PACKAGE IS STABLE ON ONE MACHINE. IT WAS NOT STABLE BETWEEN TWO.
 *
 * `withStatedTimestamp` rewrites the package through fflate at a fixed mtime, and fflate packs the
 * DOS stamp from `getHours()`, `getDate()` and friends — all LOCAL — applied to `new Date(mtime)`.
 * The mtime was `new Date(Date.UTC(1980, 0, 2))`, one INSTANT, and one instant is a different wall
 * clock in every zone. Measured on this draft before the fix: the stamp was 0x220000 under UTC,
 * 0x219800 under America/New_York, 0x224800 under Asia/Tokyo, 0x216000 under Etc/GMT+12 and
 * 0x217000 under Pacific/Kiritimati — which kept UTC-10 until 1994, so 1980-01-02T00:00Z fell on
 * the 1st there and the DATE half of the stamp moved as well. Five zones, five different documents
 * from one draft, and the packet that embeds this file inherited every one of them.
 *
 * Two runs of one suite share a timezone, which is the only reason this survived. So these tests
 * run the writer in five, by setting `process.env.TZ` around it — the switch Node reads for every
 * `Date` getter fflate calls. The five archives were checked byte for byte against five separate
 * `TZ=... node` processes and are the same files.
 *
 * Only the stated-instant path is under test. Without `generatedAtISO` the `docx` library's own
 * wall-clock stamp is kept and the bytes are meant to vary; `DocxOptions` says so in writing.
 */
const TIMEZONES = ['UTC', 'America/New_York', 'Asia/Tokyo', 'Etc/GMT+12', 'Pacific/Kiritimati'];

/** Writes as a machine in `tz` would, and puts the zone back even if the writer throws. */
async function inTimeZone<T>(tz: string, write: () => Promise<T>): Promise<T> {
  const previous = process.env.TZ;
  process.env.TZ = tz;
  try {
    return await write();
  } finally {
    if (previous === undefined) delete process.env.TZ;
    else process.env.TZ = previous;
  }
}

/**
 * 1980-01-02 00:00:00 packed the way ZIP stores it: date `((1980 - 1980) << 9) | (1 << 5) | 2` in
 * the high half, midnight — zero — in the low half. It is a LOCAL wall clock, so a writer that has
 * stopped depending on the machine packs this one number everywhere on earth.
 *
 * Read at offset 10, which is neither a guess nor a scan: the first local file header sits at byte
 * 0 of every ZIP and carries its DOS stamp at +10. `PK\x03\x04` also occurs inside deflated
 * payloads, so hunting for the later headers would find phantoms — the byte-identity test covers
 * the rest of the entries, since a stamp that moved in any of them would move the bytes.
 */
const DOS_1980_01_02 = 0x0022_0000;

describe('the DOCX is the same file on any machine, not merely on one machine twice', () => {
  const draft = markdownToDraft(MD, META);
  const opts = { generatedAtISO: '2026-08-02T12:00:00.000Z' };

  it('writes identical bytes from UTC−12 to the far side of the date line', async () => {
    const written = new Map<string, Buffer>();
    for (const tz of TIMEZONES) {
      written.set(tz, await inTimeZone(tz, () => draftToDocx(draft, opts)));
    }
    const reference = written.get('UTC') as Buffer;
    for (const [tz, bytes] of written) {
      expect(bytes.equals(reference), `${tz} writes a different document from UTC`).toBe(true);
    }
  });

  it('stamps the package 1980-01-02 00:00 local, whatever local happens to mean', async () => {
    for (const tz of TIMEZONES) {
      const buf = await inTimeZone(tz, () => draftToDocx(draft, opts));
      expect(buf.readUInt32LE(10), `${tz} packs a different DOS stamp`).toBe(DOS_1980_01_02);
    }
  });

  /**
   * A stamp outside 1980-2099 does not produce a wrong package, it produces NO package: fflate
   * 0.8.3 throws "date not in range 1980-2099". These two zones are where that used to bite, which
   * is why they are the ones this test opens the result in.
   *
   * The hazard belonged to the OLD instant form, not to the current one, and the first version of
   * this comment blamed the wrong thing — see the corrected note on `ARCHIVE_MTIME` in `docx.ts`.
   * A zoneless date-time string is 1 January in every zone by construction, so neither candidate
   * date can underflow; the 2nd is retained because it is what already shipped.
   */
  it('is still a readable OPC package when it was written in the most distant zones', async () => {
    for (const tz of ['Etc/GMT+12', 'Pacific/Kiritimati']) {
      const buf = await inTimeZone(tz, () => draftToDocx(draft, opts));
      const entries = parts(buf);
      for (const required of ['[Content_Types].xml', '_rels/.rels', 'word/document.xml']) {
        expect(Object.keys(entries), `${tz} produced an unreadable package`).toContain(required);
      }
      expect(documentXml(buf)).toContain('Need statement');
    }
  });
});

// ---------------------------------------------------------------------------
// THE EXPORT GATE (spec §10.4). Plan 4 owns it; this proves the export path
// cannot render a draft that has not been through it.
// ---------------------------------------------------------------------------

const APPLICATIONS_DDL = `
  CREATE TABLE applications (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    program_id TEXT,
    title TEXT NOT NULL,
    body_markdown TEXT NOT NULL DEFAULT '',
    answers_json TEXT NOT NULL DEFAULT '{}',
    fact_confirmations_json TEXT NOT NULL DEFAULT '{}',
    include_disclosure INTEGER NOT NULL DEFAULT 1,
    facts_confirmed_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );
  CREATE TABLE profiles (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    kind TEXT NOT NULL,
    data TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (user_id, kind)
  );`;

const NOW = '2026-08-02T12:00:00.000Z';
const clock = (): string => NOW;

function draftWith(body: string): { db: Database.Database; id: string } {
  const db = new Database(':memory:');
  db.exec(APPLICATIONS_DDL);
  const app = createApplication(db, { userId: 'user-1', title: 'Draft' }, clock);
  updateApplication(db, app.id, 'user-1', { bodyMarkdown: body }, clock);
  return { db, id: app.id };
}

function confirmEverything(db: Database.Database, id: string, body: string): void {
  const incoming = Object.fromEntries(
    extractFactAssertions(body).map((f) => [f.id, { confirmed: true, note: '' }]),
  );
  setFactConfirmations(db, id, 'user-1', resolveConfirmations(body, incoming).resolved, clock);
}

/** What the export route does, in the route's order. A renderer never runs before the gate. */
async function exportDraft(db: Database.Database, id: string, body: string): Promise<Buffer> {
  assertExportReady(db, id, 'user-1');
  return draftToDocx(markdownToDraft(body, META));
}

describe('the export gate refuses a draft the applicant has not signed off', () => {
  it('throws 409 for an unconfirmed factual assertion, and renders nothing', async () => {
    const body = '# Budget\n\nOne transceiver at $2,899.';
    const { db, id } = draftWith(body);
    await expect(exportDraft(db, id, body)).rejects.toThrow(AppError);
    await expect(exportDraft(db, id, body)).rejects.toMatchObject({ code: 'conflict', status: 409 });
  });

  it('throws 409 while a [TODO: …] marker is still open', async () => {
    const body = "# Need statement\n\nOur club needs [TODO: club.callsign — the club's callsign, e.g. W8UM].";
    const { db, id } = draftWith(body);
    await expect(exportDraft(db, id, body)).rejects.toMatchObject({ code: 'conflict', status: 409 });
  });

  it('renders once every assertion is confirmed and no gap is left', async () => {
    const body = '# Budget\n\nOne transceiver at $2,899.';
    const { db, id } = draftWith(body);
    confirmEverything(db, id, body);
    const buf = await exportDraft(db, id, body);
    expect(buf.subarray(0, 2).toString('latin1')).toBe('PK');
    expect(documentXml(buf)).toContain('$2,899');
  });

  /**
   * A confirmation is FINGERPRINTED, so ticking `$1,450` does not silently carry over to `$9,999`
   * typed at the same character width — the id is a position, and a position alone would.
   */
  it('re-blocks the export when a confirmed figure is edited to another of the same width', async () => {
    const before = '# Budget\n\nOne transceiver at $1,450.';
    const after = '# Budget\n\nOne transceiver at $9,999.';
    const { db, id } = draftWith(before);
    confirmEverything(db, id, before);
    await expect(exportDraft(db, id, before)).resolves.toBeInstanceOf(Buffer);

    updateApplication(db, id, 'user-1', { bodyMarkdown: after }, clock);
    await expect(exportDraft(db, id, after)).rejects.toMatchObject({ code: 'conflict', status: 409 });
  });

  it('answers 404, never 409, for a draft belonging to somebody else', () => {
    const { db, id } = draftWith('# S\n\nNo facts here at all.');
    expect(() => assertExportReady(db, id, 'user-2')).toThrow(AppError);
    try {
      assertExportReady(db, id, 'user-2');
    } catch (error) {
      expect((error as AppError).code).toBe('not_found');
    }
  });
});
