import { strFromU8, unzipSync } from 'fflate';
import { describe, expect, it } from 'vitest';
import { markdownToDraft } from './draft.js';
import type { BudgetLine } from './packet.js';
import { makeFunder, makeProgram } from './testFixtures.js';
import {
  budgetWorksheetCsv,
  buildApplicationPacket,
  requirementsChecklistMarkdown,
  sourceLinksMarkdown,
} from './zip.js';

const LINES: BudgetLine[] = [
  {
    item: 'IC-7610 transceiver',
    category: 'Equipment',
    quantity: 1,
    unitCost: 2899,
    justification: 'Replaces a 1998 radio',
    quoteSource: 'https://www.example.org/quote-2026-07',
  },
  {
    item: 'Coaxial cable, 200 ft',
    category: 'Materials',
    quantity: 2,
    unitCost: 145.5,
    justification: 'Feedline replacement',
    quoteSource: 'https://www.example.org/quote-2026-07',
  },
];

const PROGRAM = makeProgram({
  fundingRestrictions: ['No emergency-communications equipment', 'No ongoing operating expenses'],
  obligations: {
    costShareRequired: false,
    coFunderPreference: true,
    indirectCostCapPct: 20,
    licenseObligation: 'All output must be open-source or open-access (GPL, MIT, BSD, CERN-OHL or CC).',
  },
  constraints: [
    {
      id: 'c-hard-entity',
      hard: true,
      fallbackRank: 0,
      rawText: 'Applicant must be a US 501(c)(3), government body, school or university.',
      spec: { axis: 'other', note: 'US 501(c)(3), government, school or university' },
    },
    {
      id: 'c-soft-gpa',
      hard: false,
      fallbackRank: 0,
      rawText: 'Preference is given to applicants with a GPA over 3.5.',
      spec: { axis: 'gpa', min: 3.5 },
    },
  ],
});

const GENERATED_AT = '2026-08-02T12:00:00.000Z';

function packetInput(overrides: Partial<Parameters<typeof buildApplicationPacket>[0]> = {}) {
  const draft = markdownToDraft('# Need statement\n\nText.', {
    title: 'Draft',
    provenanceNote: 'Generated by GrantSpotter on 2026-08-02.',
  });
  return {
    program: PROGRAM,
    funder: makeFunder(),
    draft,
    budgetLines: LINES,
    generatedAtISO: GENERATED_AT,
    ...overrides,
  };
}

/** Every packet entry as text — the nested DOCX expanded, so nothing hides inside a second ZIP. */
function packetText(zip: Uint8Array): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [name, data] of Object.entries(unzipSync(zip))) {
    if (name.endsWith('.docx')) {
      for (const [inner, innerData] of Object.entries(unzipSync(data))) {
        if (inner.endsWith('.xml') || inner.endsWith('.rels')) out[`${name}!${inner}`] = strFromU8(innerData);
      }
      continue;
    }
    out[name] = strFromU8(data);
  }
  return out;
}

// ---------------------------------------------------------------------------
// budgetWorksheetCsv
// ---------------------------------------------------------------------------

describe('budgetWorksheetCsv', () => {
  it('computes line totals and a grand total', () => {
    const csv = budgetWorksheetCsv(LINES, PROGRAM);
    expect(csv).toContain('IC-7610 transceiver');
    expect(csv).toContain('2899');
    expect(csv).toContain('291'); // 2 x 145.50
    expect(csv).toContain('TOTAL');
    expect(csv).toContain('3190');
  });

  it('adds an indirect-cost cap row when the funder caps indirect costs', () => {
    const csv = budgetWorksheetCsv(LINES, PROGRAM);
    expect(csv).toContain('Indirect cost cap (20%)');
    expect(csv).toContain('638'); // 20% of 3190
  });

  it('omits the indirect row when the funder sets no cap', () => {
    expect(budgetWorksheetCsv(LINES, makeProgram())).not.toContain('Indirect cost cap');
  });

  /**
   * `costShareRequired` is UNSTATED on 148 of the 150 publishable programmes and `false` on ZERO.
   * A worksheet that answered the matching-funds question with silence — or worse, with "no match
   * required" — would put a claim in the applicant's budget that no funder has made.
   */
  it('says the funder has not addressed cost share, and never that no match is required', () => {
    const csv = budgetWorksheetCsv(LINES, makeProgram());
    expect(csv).toContain('Cost share');
    expect(csv).toMatch(/has not said|not stated|unstated/i);
    expect(csv).not.toMatch(/no match(ing)? (is )?(funds? )?required/i);
    expect(csv).not.toMatch(/cost share is not required/i);
  });

  it('reports a stated obligation as stated, in both directions', () => {
    expect(budgetWorksheetCsv(LINES, PROGRAM)).toMatch(/is not required/i);
    const required = makeProgram({ obligations: { costShareRequired: true } });
    expect(budgetWorksheetCsv(LINES, required)).toMatch(/is required/i);
  });
});

// ---------------------------------------------------------------------------
// requirementsChecklistMarkdown
// ---------------------------------------------------------------------------

describe('requirementsChecklistMarkdown', () => {
  const md = requirementsChecklistMarkdown(PROGRAM, makeFunder());

  it('separates hard requirements from preferences and never calls a preference a requirement', () => {
    const hardIdx = md.indexOf('## Requirements (must be true)');
    const softIdx = md.indexOf('## Preferences (these rank you, they never exclude you)');
    expect(hardIdx).toBeGreaterThan(-1);
    expect(softIdx).toBeGreaterThan(hardIdx);
    expect(md.slice(hardIdx, softIdx)).toContain('US 501(c)(3)');
    expect(md.slice(softIdx)).toContain('GPA over 3.5');
  });

  it('lists funding restrictions and obligations as checkboxes', () => {
    expect(md).toContain('- [ ] No emergency-communications equipment');
    expect(md).toContain('- [ ] No ongoing operating expenses');
    expect(md).toContain('open-source or open-access');
    expect(md).toContain('Indirect costs capped at 20%');
    expect(md).toContain('prefers not to be the sole funder');
  });

  it('states how to apply and the last-verified provenance', () => {
    expect(md).toContain('external_spa_portal');
    expect(md).toContain('https://www.ardc.net/apply/');
    expect(md).toContain('last verified 2026-08-02');
  });

  /**
   * Only 4 of the 243 cycles this corpus carries are dates a funder published; the other 239 are
   * computed from a recurrence rule. A checklist that printed one as "the deadline" is the exact
   * failure this project spent the most effort removing, so it prints the funder's own deadline
   * words and NO computed date at all, and says which is which.
   */
  it('quotes the funder’s own deadline words and no projected date', () => {
    expect(md).toContain('February 1, April 1, July 1, September 1.');
    expect(md).toMatch(/projects most cycle dates from a recurrence rule/i);
    // The only ISO date the file may carry is the provenance stamp saying when we last read the
    // page. Any other would be a date GrantSpotter computed, wearing the funder's authority.
    const withoutProvenance = md
      .split('\n')
      .filter((line) => !line.includes('last verified'))
      .join('\n');
    expect(withoutProvenance).not.toMatch(/\b20\d{2}-\d{2}-\d{2}\b/);
  });

  it('reports an unstated obligation as unstated rather than omitting the question', () => {
    const bare = requirementsChecklistMarkdown(makeProgram(), makeFunder());
    expect(bare).toMatch(/Cost share[^\n]*has not said/i);
    expect(bare).not.toMatch(/cost share is not required/i);
  });

  it('marks an inherited deadline as somebody else’s, because 111 ARRL entries share one', () => {
    const inherited = makeProgram({
      deadline: { kind: 'inherited', source: { kind: 'inherited', fromProgramId: 'arrl-foundation' }, note: 'One application, one deadline.' },
    });
    expect(requirementsChecklistMarkdown(inherited, makeFunder())).toContain('arrl-foundation');
  });
});

// ---------------------------------------------------------------------------
// sourceLinksMarkdown
// ---------------------------------------------------------------------------

describe('sourceLinksMarkdown', () => {
  it('links the funder homepage, the source URL and the apply URL', () => {
    const md = sourceLinksMarkdown(PROGRAM, makeFunder());
    expect(md).toContain('https://www.ardc.net/');
    expect(md).toContain('https://www.ardc.net/apply/');
  });

  it('renders a disputed block when the record carries one', () => {
    const disputed = makeProgram({
      trust: {
        ...PROGRAM.trust,
        disputed: {
          note: 'Three researchers reached three different conclusions about this cycle.',
          claims: [
            { claim: 'Dormant; no open cycle published', sourceUrl: 'https://www.arrl.org/club-grant-program' },
            { claim: 'Autumn window, historically Sep 7 to Nov 4', sourceUrl: 'https://www.arrl.org/news' },
          ],
        },
      },
    });
    const md = sourceLinksMarkdown(disputed, undefined);
    expect(md).toContain('## Disputed');
    expect(md).toContain('Three researchers');
    expect(md).toContain('Autumn window');
  });

  it('withholds a blocklisted address instead of printing it as a source', () => {
    const hijacked = makeProgram({
      applyUrl: 'https://www.farweb.org/scholarships',
      trust: { ...PROGRAM.trust, sourceUrl: 'https://www.qcwa.org/scholarships.htm' },
    });
    const md = sourceLinksMarkdown(hijacked, makeFunder({ homepage: 'http://farweb.org/' }));
    expect(md).not.toMatch(/farweb/i);
    expect(md).toContain('link withheld');
  });
});

// ---------------------------------------------------------------------------
// buildApplicationPacket
// ---------------------------------------------------------------------------

describe('buildApplicationPacket', () => {
  it('contains exactly the six packet entries', async () => {
    const entries = unzipSync(await buildApplicationPacket(packetInput()));
    expect(Object.keys(entries).sort()).toEqual([
      'README.txt',
      'budget-worksheet.csv',
      'draft.docx',
      'draft.md',
      'requirements-checklist.md',
      'source-links.md',
    ]);
    expect(strFromU8(entries['README.txt'] as Uint8Array)).toContain('ARDC Grants Program');
    expect(strFromU8(entries['draft.md'] as Uint8Array)).toContain('# Need statement');
    expect((entries['draft.docx'] as Uint8Array).subarray(0, 2)).toEqual(new Uint8Array([0x50, 0x4b]));
  });

  it('ships a DOCX the packet reader can open and read the draft out of', async () => {
    const entries = unzipSync(await buildApplicationPacket(packetInput()));
    const inner = unzipSync(entries['draft.docx'] as Uint8Array);
    expect(Object.keys(inner)).toContain('word/document.xml');
    expect(strFromU8(inner['word/document.xml'] as Uint8Array)).toContain('Need statement');
  });

  it('is byte-identical across two runs with the same input', async () => {
    const input = packetInput();
    const a = await buildApplicationPacket(input);
    const b = await buildApplicationPacket(input);
    expect(Buffer.from(a).equals(Buffer.from(b))).toBe(true);
  });

  it('names its own contents in the README, so no entry is a mystery', async () => {
    const readme = packetText(await buildApplicationPacket(packetInput()))['README.txt'] ?? '';
    for (const entry of [
      'draft.md',
      'draft.docx',
      'budget-worksheet.csv',
      'requirements-checklist.md',
      'source-links.md',
    ]) {
      expect(readme).toContain(entry);
    }
  });

  /**
   * `farweb.org` must not reach a funder's inbox as an address, in ANY entry — not in the source
   * list, not in a verbatim quote of the funder's own page, not in a budget quote URL a user
   * typed, and not compressed inside the DOCX where a byte search of the outer ZIP would miss it.
   */
  it('carries no blocklisted host in any entry, including inside the DOCX', async () => {
    const hijacked = makeProgram({
      applyUrl: 'https://www.farweb.org/scholarships',
      applyContact: 'See farweb.org for the packet.',
      rawOtherText: 'Applicants should apply at the FAR website, http://www.farweb.org/apply.html.',
      trust: { ...PROGRAM.trust, sourceUrl: 'https://www.qcwa.org/scholarships.htm' },
    });
    const zip = await buildApplicationPacket(
      packetInput({
        program: hijacked,
        funder: makeFunder({ homepage: 'https://farweb.org/' }),
        draft: markdownToDraft('# Need\n\nWe were told to apply at https://www.farweb.org/apply.html.', {
          title: 'Draft',
          provenanceNote: 'note',
        }),
        budgetLines: [{ ...(LINES[0] as BudgetLine), quoteSource: 'http://farweb.org/quote' }],
      }),
    );
    const text = packetText(zip);
    expect(Object.keys(text).length).toBeGreaterThan(6);
    for (const [name, body] of Object.entries(text)) {
      expect(body, `${name} carries the hijacked host`).not.toMatch(/farweb/i);
      expect(body, `${name} carries the takeover target`).not.toMatch(/batualam/i);
    }
    expect(text['source-links.md']).toContain('link withheld');
  });

  it('tells the reader in the README that GrantSpotter vouches for nothing in the packet', async () => {
    const readme = packetText(await buildApplicationPacket(packetInput()))['README.txt'] ?? '';
    expect(readme).toContain('did not write your application');
    expect(readme).toContain('Verify each one before you submit.');
  });
});
