import { strFromU8, unzipSync } from 'fflate';
import { describe, expect, it } from 'vitest';
import { markdownToDraft } from './draft.js';
import type { BudgetLine } from './packet.js';
import { makeFunder, makeProgram } from './testFixtures.js';
import {
  budgetWorksheetCsv,
  buildApplicationPacket,
  requirementsChecklistMarkdown,
  sourceLinksMarkdown,
} from './zip.js';

const LINES: BudgetLine[] = [
  {
    item: 'IC-7610 transceiver',
    category: 'Equipment',
    quantity: 1,
    unitCost: 2899,
    justification: 'Replaces a 1998 radio',
    quoteSource: 'https://www.example.org/quote-2026-07',
  },
  {
    item: 'Coaxial cable, 200 ft',
    category: 'Materials',
    quantity: 2,
    unitCost: 145.5,
    justification: 'Feedline replacement',
    quoteSource: 'https://www.example.org/quote-2026-07',
  },
];

const PROGRAM = makeProgram({
  fundingRestrictions: ['No emergency-communications equipment', 'No ongoing operating expenses'],
  obligations: {
    costShareRequired: false,
    coFunderPreference: true,
    indirectCostCapPct: 20,
    licenseObligation: 'All output must be open-source or open-access (GPL, MIT, BSD, CERN-OHL or CC).',
  },
  constraints: [
    {
      id: 'c-hard-entity',
      hard: true,
      fallbackRank: 0,
      rawText: 'Applicant must be a US 501(c)(3), government body, school or university.',
      spec: { axis: 'other', note: 'US 501(c)(3), government, school or university' },
    },
    {
      id: 'c-soft-gpa',
      hard: false,
      fallbackRank: 0,
      rawText: 'Preference is given to applicants with a GPA over 3.5.',
      spec: { axis: 'gpa', min: 3.5 },
    },
  ],
});

const GENERATED_AT = '2026-08-02T12:00:00.000Z';

function packetInput(overrides: Partial<Parameters<typeof buildApplicationPacket>[0]> = {}) {
  const draft = markdownToDraft('# Need statement\n\nText.', {
    title: 'Draft',
    provenanceNote: 'Generated by GrantSpotter on 2026-08-02.',
  });
  return {
    program: PROGRAM,
    funder: makeFunder(),
    draft,
    budgetLines: LINES,
    generatedAtISO: GENERATED_AT,
    ...overrides,
  };
}

/** Every packet entry as text — the nested DOCX expanded, so nothing hides inside a second ZIP. */
function packetText(zip: Uint8Array): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [name, data] of Object.entries(unzipSync(zip))) {
    if (name.endsWith('.docx')) {
      for (const [inner, innerData] of Object.entries(unzipSync(data))) {
        if (inner.endsWith('.xml') || inner.endsWith('.rels')) out[`${name}!${inner}`] = strFromU8(innerData);
      }
      continue;
    }
    out[name] = strFromU8(data);
  }
  return out;
}

// ---------------------------------------------------------------------------
// budgetWorksheetCsv
// ---------------------------------------------------------------------------

describe('budgetWorksheetCsv', () => {
  it('computes line totals and a grand total', () => {
    const csv = budgetWorksheetCsv(LINES, PROGRAM);
    expect(csv).toContain('IC-7610 transceiver');
    expect(csv).toContain('2899');
    expect(csv).toContain('291'); // 2 x 145.50
    expect(csv).toContain('TOTAL');
    expect(csv).toContain('3190');
  });

  it('adds an indirect-cost cap row when the funder caps indirect costs', () => {
    const csv = budgetWorksheetCsv(LINES, PROGRAM);
    expect(csv).toContain('Indirect cost cap (20%)');
    expect(csv).toContain('638'); // 20% of 3190
  });

  it('omits the indirect row when the funder sets no cap', () => {
    expect(budgetWorksheetCsv(LINES, makeProgram())).not.toContain('Indirect cost cap');
  });

  /**
   * `costShareRequired` is UNSTATED on 148 of the 150 publishable programmes and `false` on ZERO.
   * A worksheet that answered the matching-funds question with silence — or worse, with "no match
   * required" — would put a claim in the applicant's budget that no funder has made.
   */
  it('says the funder has not addressed cost share, and never that no match is required', () => {
    const csv = budgetWorksheetCsv(LINES, makeProgram());
    expect(csv).toContain('Cost share');
    expect(csv).toMatch(/has not said|not stated|unstated/i);
    expect(csv).not.toMatch(/no match(ing)? (is )?(funds? )?required/i);
    expect(csv).not.toMatch(/cost share is not required/i);
  });

  it('reports a stated obligation as stated, in both directions', () => {
    expect(budgetWorksheetCsv(LINES, PROGRAM)).toMatch(/is not required/i);
    const required = makeProgram({ obligations: { costShareRequired: true } });
    expect(budgetWorksheetCsv(LINES, required)).toMatch(/is required/i);
  });
});

// ---------------------------------------------------------------------------
// requirementsChecklistMarkdown
// ---------------------------------------------------------------------------

describe('requirementsChecklistMarkdown', () => {
  const md = requirementsChecklistMarkdown(PROGRAM, makeFunder());

  it('separates hard requirements from preferences and never calls a preference a requirement', () => {
    const hardIdx = md.indexOf('## Requirements (must be true)');
    const softIdx = md.indexOf('## Preferences (these rank you, they never exclude you)');
    expect(hardIdx).toBeGreaterThan(-1);
    expect(softIdx).toBeGreaterThan(hardIdx);
    expect(md.slice(hardIdx, softIdx)).toContain('US 501(c)(3)');
    expect(md.slice(softIdx)).toContain('GPA over 3.5');
  });

  it('lists funding restrictions and obligations as checkboxes', () => {
    expect(md).toContain('- [ ] No emergency-communications equipment');
    expect(md).toContain('- [ ] No ongoing operating expenses');
    expect(md).toContain('open-source or open-access');
    expect(md).toContain('Indirect costs capped at 20%');
    expect(md).toContain('prefers not to be the sole funder');
  });

  it('states how to apply and the last-verified provenance', () => {
    expect(md).toContain('external_spa_portal');
    expect(md).toContain('https://www.ardc.net/apply/');
    expect(md).toContain('last verified 2026-08-02');
  });

  /**
   * Only 4 of the 243 cycles this corpus carries are dates a funder published; the other 239 are
   * computed from a recurrence rule. A checklist that printed one as "the deadline" is the exact
   * failure this project spent the most effort removing, so it prints the funder's own deadline
   * words and NO computed date at all, and says which is which.
   */
  it('quotes the funder’s own deadline words and no projected date', () => {
    expect(md).toContain('February 1, April 1, July 1, September 1.');
    expect(md).toMatch(/projects most cycle dates from a recurrence rule/i);
    // The only ISO date the file may carry is the provenance stamp saying when we last read the
    // page. Any other would be a date GrantSpotter computed, wearing the funder's authority.
    const withoutProvenance = md
      .split('\n')
      .filter((line) => !line.includes('last verified'))
      .join('\n');
    expect(withoutProvenance).not.toMatch(/\b20\d{2}-\d{2}-\d{2}\b/);
  });

  it('reports an unstated obligation as unstated rather than omitting the question', () => {
    const bare = requirementsChecklistMarkdown(makeProgram(), makeFunder());
    expect(bare).toMatch(/Cost share[^\n]*has not said/i);
    expect(bare).not.toMatch(/cost share is not required/i);
  });

  it('marks an inherited deadline as somebody else’s, because 111 ARRL entries share one', () => {
    const inherited = makeProgram({
      deadline: { kind: 'inherited', source: { kind: 'inherited', fromProgramId: 'arrl-foundation' }, note: 'One application, one deadline.' },
    });
    expect(requirementsChecklistMarkdown(inherited, makeFunder())).toContain('arrl-foundation');
  });
});

// ---------------------------------------------------------------------------
// sourceLinksMarkdown
// ---------------------------------------------------------------------------

describe('sourceLinksMarkdown', () => {
  it('links the funder homepage, the source URL and the apply URL', () => {
    const md = sourceLinksMarkdown(PROGRAM, makeFunder());
    expect(md).toContain('https://www.ardc.net/');
    expect(md).toContain('https://www.ardc.net/apply/');
  });

  it('renders a disputed block when the record carries one', () => {
    const disputed = makeProgram({
      trust: {
        ...PROGRAM.trust,
        disputed: {
          note: 'Three researchers reached three different conclusions about this cycle.',
          claims: [
            { claim: 'Dormant; no open cycle published', sourceUrl: 'https://www.arrl.org/club-grant-program' },
            { claim: 'Autumn window, historically Sep 7 to Nov 4', sourceUrl: 'https://www.arrl.org/news' },
          ],
        },
      },
    });
    const md = sourceLinksMarkdown(disputed, undefined);
    expect(md).toContain('## Disputed');
    expect(md).toContain('Three researchers');
    expect(md).toContain('Autumn window');
  });

  it('withholds a blocklisted address instead of printing it as a source', () => {
    const hijacked = makeProgram({
      applyUrl: 'https://www.farweb.org/scholarships',
      trust: { ...PROGRAM.trust, sourceUrl: 'https://www.qcwa.org/scholarships.htm' },
    });
    const md = sourceLinksMarkdown(hijacked, makeFunder({ homepage: 'http://farweb.org/' }));
    expect(md).not.toMatch(/farweb/i);
    expect(md).toContain('link withheld');
  });
});

// ---------------------------------------------------------------------------
// buildApplicationPacket
// ---------------------------------------------------------------------------

describe('buildApplicationPacket', () => {
  it('contains exactly the six packet entries', async () => {
    const entries = unzipSync(await buildApplicationPacket(packetInput()));
    expect(Object.keys(entries).sort()).toEqual([
      'README.txt',
      'budget-worksheet.csv',
      'draft.docx',
      'draft.md',
      'requirements-checklist.md',
      'source-links.md',
    ]);
    expect(strFromU8(entries['README.txt'] as Uint8Array)).toContain('ARDC Grants Program');
    expect(strFromU8(entries['draft.md'] as Uint8Array)).toContain('# Need statement');
    expect((entries['draft.docx'] as Uint8Array).subarray(0, 2)).toEqual(new Uint8Array([0x50, 0x4b]));
  });

  it('ships a DOCX the packet reader can open and read the draft out of', async () => {
    const entries = unzipSync(await buildApplicationPacket(packetInput()));
    const inner = unzipSync(entries['draft.docx'] as Uint8Array);
    expect(Object.keys(inner)).toContain('word/document.xml');
    expect(strFromU8(inner['word/document.xml'] as Uint8Array)).toContain('Need statement');
  });

  it('is byte-identical across two runs with the same input', async () => {
    const input = packetInput();
    const a = await buildApplicationPacket(input);
    const b = await buildApplicationPacket(input);
    expect(Buffer.from(a).equals(Buffer.from(b))).toBe(true);
  });

  it('names its own contents in the README, so no entry is a mystery', async () => {
    const readme = packetText(await buildApplicationPacket(packetInput()))['README.txt'] ?? '';
    for (const entry of [
      'draft.md',
      'draft.docx',
      'budget-worksheet.csv',
      'requirements-checklist.md',
      'source-links.md',
    ]) {
      expect(readme).toContain(entry);
    }
  });

  /**
   * `farweb.org` must not reach a funder's inbox as an address, in ANY entry — not in the source
   * list, not in a verbatim quote of the funder's own page, not in a budget quote URL a user
   * typed, and not compressed inside the DOCX where a byte search of the outer ZIP would miss it.
   */
  it('carries no blocklisted host in any entry, including inside the DOCX', async () => {
    const hijacked = makeProgram({
      applyUrl: 'https://www.farweb.org/scholarships',
      applyContact: 'See farweb.org for the packet.',
      rawOtherText: 'Applicants should apply at the FAR website, http://www.farweb.org/apply.html.',
      trust: { ...PROGRAM.trust, sourceUrl: 'https://www.qcwa.org/scholarships.htm' },
    });
    const zip = await buildApplicationPacket(
      packetInput({
        program: hijacked,
        funder: makeFunder({ homepage: 'https://farweb.org/' }),
        draft: markdownToDraft('# Need\n\nWe were told to apply at https://www.farweb.org/apply.html.', {
          title: 'Draft',
          provenanceNote: 'note',
        }),
        budgetLines: [{ ...(LINES[0] as BudgetLine), quoteSource: 'http://farweb.org/quote' }],
      }),
    );
    const text = packetText(zip);
    expect(Object.keys(text).length).toBeGreaterThan(6);
    for (const [name, body] of Object.entries(text)) {
      expect(body, `${name} carries the hijacked host`).not.toMatch(/farweb/i);
      expect(body, `${name} carries the takeover target`).not.toMatch(/batualam/i);
    }
    expect(text['source-links.md']).toContain('link withheld');
  });

  it('tells the reader in the README that GrantSpotter vouches for nothing in the packet', async () => {
    const readme = packetText(await buildApplicationPacket(packetInput()))['README.txt'] ?? '';
    expect(readme).toContain('did not write your application');
    expect(readme).toContain('Verify each one before you submit.');
  });
});

// ---------------------------------------------------------------------------
// The packet container, on a machine that is not this one
// ---------------------------------------------------------------------------

/**
 * THE MACHINE'S TIMEZONE WAS PART OF THE PACKET'S BYTES, AND EVERY PROOF ABOVE HELD ONLY INSIDE
 * ONE ZONE.
 *
 * fflate packs the DOS stamp from `getHours()`, `getDate()` and friends — all LOCAL — applied to
 * `new Date(mtime)`. The fixed mtime was `new Date(Date.UTC(1980, 0, 2))`, one INSTANT, and one
 * instant is a different wall clock in every zone. Measured on this corpus before the fix: the
 * stamp was 0x220000 under UTC, 0x219800 under America/New_York, 0x224800 under Asia/Tokyo,
 * 0x216000 under Etc/GMT+12 and 0x217000 under Pacific/Kiritimati — which kept UTC-10 until 1994,
 * so 1980-01-02T00:00Z landed on the 1st there and the DATE half of the stamp moved too. Five
 * zones, five different packets from one input.
 *
 * 'is byte-identical across two runs with the same input' could not see any of it: two runs of one
 * suite share a timezone. So these tests do not stay in one. They set `process.env.TZ` around the
 * writer, which is the switch Node reads for every `Date` getter fflate calls; the five archives
 * that produces were checked byte for byte against five separate `TZ=... node` processes and are
 * the same files.
 */
const TIMEZONES = ['UTC', 'America/New_York', 'Asia/Tokyo', 'Etc/GMT+12', 'Pacific/Kiritimati'];

/** Builds as a machine in `tz` would, and puts the zone back even if the writer throws. */
async function inTimeZone<T>(tz: string, build: () => Promise<T>): Promise<T> {
  const previous = process.env.TZ;
  process.env.TZ = tz;
  try {
    return await build();
  } finally {
    if (previous === undefined) delete process.env.TZ;
    else process.env.TZ = previous;
  }
}

/**
 * 1980-01-02 00:00:00 packed the way ZIP stores it: date `((1980 - 1980) << 9) | (1 << 5) | 2` in
 * the high half, midnight — zero — in the low half. It is a LOCAL wall clock, so a writer that has
 * stopped depending on the machine packs this one number everywhere on earth.
 *
 * Read at offset 10, which is not a guess and not a scan: the first local file header sits at byte
 * 0 of every ZIP and carries its DOS stamp at +10. `PK\x03\x04` also occurs inside deflated
 * payloads, so a search for the later headers would find phantoms — the byte-identity test above
 * covers the remaining entries, since a stamp that moved in any of them would move the bytes.
 */
const DOS_1980_01_02 = 0x0022_0000;

describe('the packet is the same file on any machine, not merely on one machine twice', () => {
  it('packs identical bytes from UTC−12 to the far side of the date line', async () => {
    const input = packetInput();
    const built = new Map<string, Buffer>();
    for (const tz of TIMEZONES) {
      built.set(tz, Buffer.from(await inTimeZone(tz, () => buildApplicationPacket(input))));
    }
    const reference = built.get('UTC') as Buffer;
    for (const [tz, bytes] of built) {
      expect(bytes.equals(reference), `${tz} packs a different packet from UTC`).toBe(true);
    }
  });

  it('stamps the archive 1980-01-02 00:00 local, whatever local happens to mean', async () => {
    for (const tz of TIMEZONES) {
      const packet = Buffer.from(await inTimeZone(tz, () => buildApplicationPacket(packetInput())));
      expect(packet.readUInt32LE(10), `${tz} packs a different DOS stamp`).toBe(DOS_1980_01_02);
    }
  });

  /**
   * A stamp outside 1980-2099 does not produce a wrong archive, it produces NO archive: fflate
   * 0.8.3 throws "date not in range 1980-2099". These two zones are where that used to bite, so
   * they are the ones worth opening the result in.
   *
   * They no longer bite, and the reason is worth stating precisely because the first version of
   * this comment got it backwards. The 1979 hazard was a property of the OLD `new Date(Date.UTC(…))`
   * form: one instant is a different wall clock everywhere, so midnight UTC on the 1st read back as
   * 31 December 1979 in any zone behind UTC and fflate refused to build. The date is now a zoneless
   * STRING, which is 1 January in every zone by construction, so the hazard cannot arise for either
   * candidate date — measured across every zone in this host's tzdata: both the 1st and the 2nd
   * yield exactly one stamp and throw in zero zones. The 2nd is kept because it is what already
   * shipped, and moving it would rewrite the bytes of every archive for no gain.
   */
  it('still opens, with all six entries, when it was written in the most distant zones', async () => {
    for (const tz of ['Etc/GMT+12', 'Pacific/Kiritimati']) {
      const packet = await inTimeZone(tz, () => buildApplicationPacket(packetInput()));
      const entries = unzipSync(packet);
      expect(Object.keys(entries).sort(), `${tz} produced an unreadable packet`).toEqual([
        'README.txt',
        'budget-worksheet.csv',
        'draft.docx',
        'draft.md',
        'requirements-checklist.md',
        'source-links.md',
      ]);
      expect(strFromU8(entries['draft.md'] as Uint8Array)).toContain('# Need statement');
    }
  });
});
